#!/usr/bin/env python3
"""
Color Preset Converter: TSV to C++ Color Preset Arrays (Proof of Concept)
Usage: python color_preset_converter_POC.py [color_presets.tsv]
Output: SDK_ProcAmp_ColorPresets.h

This is a proof-of-concept demonstrating the feasibility of the color preset
TSV conversion system, analogous to the existing preset_converter.py for effect presets.
"""

import sys
import csv
import os

def parse_tsv(filepath):
    """Parse TSV file and return list of color preset dictionaries"""
    presets = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            preset = {
                'id': int(row['id']),
                'name': row['name'],
                'name_en': row['name_en'],
                'colors': []
            }
            # Parse 8 colors
            for i in range(1, 9):
                color_str = row[f'color{i}']
                parts = color_str.split(',')
                if len(parts) != 4:
                    raise ValueError(f"Invalid color format in preset {preset['name']}: {color_str}")
                a, r, g, b = map(int, parts)
                # Validate range
                if not all(0 <= v <= 255 for v in [a, r, g, b]):
                    raise ValueError(f"Color values must be 0-255 in preset {preset['name']}: {color_str}")
                preset['colors'].append((a, r, g, b))
            presets.append(preset)
    return presets

def format_preset_cpp(preset):
    """Convert a preset dictionary to C++ array initializer"""
    name_en = preset['name_en']
    name_jp = preset['name']
    
    cpp = f'\t// {name_jp} ({name_en})\n'
    cpp += f'\tconst PresetColor k{name_en}[8] = {{\n'
    
    # Format colors: 4 per line for readability
    colors = []
    for a, r, g, b in preset['colors']:
        colors.append(f'{{{a}, {r}, {g}, {b}}}')
    
    for i in range(0, 8, 4):
        line = ', '.join(colors[i:i+4])
        cpp += f'\t\t{line}'
        if i + 4 < 8:
            cpp += ',\n'
        else:
            cpp += '\n'
    
    cpp += '\t};\n'
    return cpp

def generate_lookup_function(presets):
    """Generate GetPresetPalette() switch-case function"""
    cpp = '// Preset color lookup table\n'
    cpp += 'inline const PresetColor* GetPresetPalette(int presetIndex) {\n'
    cpp += '\tswitch (presetIndex) {\n'
    
    for preset in presets:
        preset_id = preset['id']
        name_en = preset['name_en']
        cpp += f'\t\tcase {preset_id}: return ColorPresets::k{name_en};\n'
    
    cpp += '\t\tdefault: return ColorPresets::kRainbow;  // Fallback to first preset\n'
    cpp += '\t}\n'
    cpp += '}\n'
    
    return cpp

def generate_cpp_header(presets):
    """Generate complete C++ header file"""
    # Header guard and comments
    cpp = '// Auto-generated by color_preset_converter.py - DO NOT EDIT MANUALLY\n'
    cpp += '// Edit color_presets.tsv and run color_preset_converter.py to regenerate\n\n'
    cpp += '#ifndef SDK_PROCAMP_COLOR_PRESETS_H\n'
    cpp += '#define SDK_PROCAMP_COLOR_PRESETS_H\n\n'
    
    # PresetColor struct definition
    cpp += '// Color structure (ARGB format)\n'
    cpp += 'struct PresetColor {\n'
    cpp += '\tunsigned char a, r, g, b;\n'
    cpp += '};\n\n'
    
    # Namespace with all preset definitions
    cpp += '// Preset color palettes (8 colors each)\n'
    cpp += 'namespace ColorPresets {\n'
    
    preset_codes = []
    for preset in presets:
        preset_codes.append(format_preset_cpp(preset))
    
    cpp += '\n'.join(preset_codes)
    cpp += '}\n\n'
    
    # Lookup function
    cpp += generate_lookup_function(presets)
    
    # Footer
    cpp += '\n#endif // SDK_PROCAMP_COLOR_PRESETS_H\n'
    
    return cpp

def main():
    # Default to same directory's color_presets.tsv
    if len(sys.argv) >= 2:
        tsv_file = sys.argv[1]
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        tsv_file = os.path.join(script_dir, 'color_presets.tsv')
    
    try:
        print(f"Reading color presets from: {tsv_file}")
        presets = parse_tsv(tsv_file)
        
        print(f"Parsed {len(presets)} color presets")
        
        cpp_code = generate_cpp_header(presets)
        
        # Save to header file in script directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_file = os.path.join(script_dir, 'SDK_ProcAmp_ColorPresets.h')
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(cpp_code)
        
        print(f"✓ Generated: {output_file}")
        print(f"✓ Total color presets: {len(presets)}")
        print(f"✓ Total colors: {len(presets) * 8}")
        
        # Summary
        print("\nPreset Summary:")
        for preset in presets:
            print(f"  [{preset['id']}] {preset['name']} ({preset['name_en']})")
        
    except FileNotFoundError:
        print(f"✗ Error: File '{tsv_file}' not found")
        print(f"  Please create a color_presets.tsv file or specify the path")
        sys.exit(1)
    except KeyError as e:
        print(f"✗ Error: Missing column in TSV: {e}")
        print(f"  Required columns: id, name, name_en, color1-color8")
        sys.exit(1)
    except ValueError as e:
        print(f"✗ Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    main()
