#!/usr/bin/env python3
"""
Preset Converter: TSV to C++ Effect Preset Array
Usage: python preset_converter.py presets.tsv
Output: C++ code for OST_WindyLines.h
"""

import sys
import csv
import os

def parse_tsv(filepath):
    """Parse TSV file and return list of preset dictionaries"""
    presets = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            presets.append(row)
    return presets

def convert_to_unified_preset_index(colorMode, presetIndex):
    """
    Convert old colorMode + presetIndex to unified preset index
    TSV colorMode values are 1-based (UI values):
      1 = 単色 (Single) → unified index 0
      2 = カスタム (Custom) → unified index 2
      3 = プリセット (Preset) → unified index 4 + presetIndex
    New structure: 単色|(-|カスタム|(-|preset1|preset2|...
    Note: Separators (-|) ARE included in menu numbering
    UI values: 1=Single, 2=Sep, 3=Custom, 4=Sep, 5=Rainbow, 6=Pastel, ...
    After normalization (0-based): 0=Single, 1=Sep, 2=Custom, 3=Sep, 4=Rainbow, 5=Pastel, ...
    """
    if colorMode == 1:
        return 0  # 単色
    elif colorMode == 2:
        return 2  # カスタム
    elif colorMode == 3:
        return 4 + presetIndex  # セパレーター(1,3)をスキップしてプリセット開始
    else:
        return 0  # Default to 単色 for invalid values

def format_preset_cpp(preset):
    """Convert a preset dictionary to C++ struct initializer"""
    # Parse values
    name = preset['name']
    count = int(float(preset['count']))
    lifetime = float(preset['lifetime'])
    travel = float(preset['travel'])
    thickness = float(preset['thickness'])
    length = float(preset['length'])
    angle = float(preset['angle'])
    tailFade = float(preset['tailFade'])
    aa = float(preset['aa'])
    originMode = int(float(preset['originMode']))
    spawnScaleX = float(preset['spawnScaleX'])
    spawnScaleY = float(preset['spawnScaleY'])
    originOffsetX = float(preset['originOffsetX'])
    originOffsetY = float(preset['originOffsetY'])
    interval = float(preset['interval'])
    animPattern = int(float(preset['animPattern']))
    centerGap = float(preset['centerGap'])
    easing = int(float(preset['easing']))
    startTime = float(preset['startTime'])
    duration = float(preset['duration'])
    blendMode = int(float(preset['blendMode']))
    depthStrength = float(preset['depthStrength'])
    lineCap = int(float(preset['lineCap']))
    colorMode = int(float(preset['colorMode']))
    colorPreset = int(float(preset['colorPreset']))
    
    # Convert to unified preset index
    unifiedPresetIndex = convert_to_unified_preset_index(colorMode, colorPreset)
    
    spawnSource = int(float(preset['spawnSource']))
    hideElement = int(float(preset['hideElement'])) != 0
    lengthLinkage = int(float(preset['lengthLinkage']))
    lengthLinkageRate = float(preset['lengthLinkageRate'])
    thicknessLinkage = int(float(preset['thicknessLinkage']))
    thicknessLinkageRate = float(preset['thicknessLinkageRate'])
    travelLinkage = int(float(preset['travelLinkage']))
    travelLinkageRate = float(preset['travelLinkageRate'])
    
    # Format as C++ struct initializer
    cpp = f'\t// {name}\n'
    cpp += f'\t{{ "{name}",\n'
    cpp += f'\t  {count}, {lifetime}f, {travel}f,\n'
    cpp += f'\t  {thickness}f, {length}f, {angle}f, {tailFade}f, {aa}f,\n'
    cpp += f'\t  {originMode}, {spawnScaleX}f, {spawnScaleY}f, {originOffsetX}f, {originOffsetY}f, {interval}f,\n'
    cpp += f'\t  {animPattern}, {centerGap}f, {easing}, {startTime}f, {duration}f,\n'
    cpp += f'\t  {blendMode}, {depthStrength}f,\n'
    cpp += f'\t  {lineCap}, {unifiedPresetIndex}, {spawnSource}, {"true" if hideElement else "false"},\n'
    cpp += f'\t  {lengthLinkage}, {lengthLinkageRate}f, {thicknessLinkage}, {thicknessLinkageRate}f, {travelLinkage}, {travelLinkageRate}f\n'
    cpp += '\t}'
    
    return cpp

def generate_cpp_array(presets):
    """Generate complete C++ array code"""
    cpp = 'static const EffectPreset kEffectPresets[] =\n{\n'
    
    preset_codes = []
    for preset in presets:
        preset_codes.append(format_preset_cpp(preset))
    
    cpp += ',\n'.join(preset_codes)
    cpp += '\n};\n'
    cpp += f'\nstatic const int kEffectPresetCount = static_cast<int>(sizeof(kEffectPresets) / sizeof(kEffectPresets[0]));\n'
    
    return cpp

def main():
    # デフォルトで同じディレクトリの presets.tsv を使用
    if len(sys.argv) >= 2:
        tsv_file = sys.argv[1]
    else:
        # スクリプトと同じディレクトリの presets.tsv を使用
        script_dir = os.path.dirname(os.path.abspath(__file__))
        tsv_file = os.path.join(script_dir, 'presets.tsv')
    
    try:
        presets = parse_tsv(tsv_file)
        cpp_code = generate_cpp_array(presets)
        
        # Save to header file in script directory
        output_file = os.path.join(script_dir, 'OST_WindyLines_Presets.h')
        
        # Add header guard
        header_content = "// Auto-generated by preset_converter.py - DO NOT EDIT MANUALLY\n"
        header_content += "// Edit presets.tsv and run preset_converter.py to regenerate\n\n"
        header_content += "#ifndef OST_WINDYLINES_PRESETS_H\n"
        header_content += "#define OST_WINDYLINES_PRESETS_H\n\n"
        header_content += cpp_code
        header_content += "\n#endif // OST_WINDYLINES_PRESETS_H\n"
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(header_content)
        
        print(f"Generated: {output_file}")
        print(f"Total presets: {len(presets)}")
        
    except FileNotFoundError:
        print(f"Error: File '{tsv_file}' not found")
        sys.exit(1)
    except KeyError as e:
        print(f"Error: Missing column in TSV: {e}")
        print("Make sure the TSV has all required columns with correct names")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
