// Auto-generated by color_preset_converter.py - DO NOT EDIT MANUALLY
// Edit color_presets.tsv and run color_preset_converter.py to regenerate

#ifndef SDK_PROCAMP_COLOR_PRESETS_H
#define SDK_PROCAMP_COLOR_PRESETS_H

// Color structure (ARGB format)
struct PresetColor {
	unsigned char a, r, g, b;
};

// Preset color palettes (8 colors each)
namespace ColorPresets {
	// レインボー (Rainbow)
	const PresetColor kRainbow[8] = {
		{255, 255, 0, 0}, {255, 255, 128, 0}, {255, 255, 255, 0}, {255, 0, 255, 0},
		{255, 0, 0, 255}, {255, 74, 0, 130}, {255, 140, 0, 255}, {255, 255, 0, 255}
	};

	// パステルレインボー (RainbowPastel)
	const PresetColor kRainbowPastel[8] = {
		{255, 255, 178, 178}, {255, 255, 217, 178}, {255, 255, 255, 178}, {255, 178, 255, 178},
		{255, 178, 178, 255}, {255, 217, 178, 255}, {255, 255, 178, 255}, {255, 255, 204, 255}
	};

	// 森 (Forest)
	const PresetColor kForest[8] = {
		{255, 102, 229, 128}, {255, 153, 242, 204}, {255, 51, 178, 229}, {255, 178, 255, 178},
		{255, 102, 204, 255}, {255, 76, 204, 102}, {255, 153, 204, 255}, {255, 204, 255, 229}
	};
}

// Preset color lookup table
inline const PresetColor* GetPresetPalette(int presetIndex) {
	switch (presetIndex) {
		case 1: return ColorPresets::kRainbow;
		case 2: return ColorPresets::kRainbowPastel;
		case 3: return ColorPresets::kForest;
		default: return ColorPresets::kRainbow;  // Fallback to first preset
	}
}

#endif // SDK_PROCAMP_COLOR_PRESETS_H
