// Auto-generated by color_preset_converter.py - DO NOT EDIT MANUALLY
// Edit color_presets.tsv and run color_preset_converter.py to regenerate

#ifndef SDK_PROCAMP_COLOR_PRESETS_H
#define SDK_PROCAMP_COLOR_PRESETS_H

// Color preset enum - auto-generated from TSV
enum ColorPreset
{
	COLOR_PRESET_RAINBOW = 1,
	COLOR_PRESET_RAINBOWPASTEL,
	COLOR_PRESET_FOREST,
	COLOR_PRESET_CYBER,
	COLOR_PRESET_HAZARD,
	COLOR_PRESET_SAKURA,
	COLOR_PRESET_DESERT,
	COLOR_PRESET_STARDUST,
	COLOR_PRESET_WAKABA,
	COLOR_PRESET_DANGERZONE,
	COLOR_PRESET_YOEN,
	COLOR_PRESET_SOKAI,
	COLOR_PRESET_DREAMYWIND,
	COLOR_PRESET_SUNSET,
	COLOR_PRESET_OCEAN,
	COLOR_PRESET_AUTUMN,
	COLOR_PRESET_SNOW,
	COLOR_PRESET_DEEPSEA,
	COLOR_PRESET_MORNINGDEW,
	COLOR_PRESET_NIGHTSKY,
	COLOR_PRESET_FLAME,
	COLOR_PRESET_EARTH,
	COLOR_PRESET_JEWEL,
	COLOR_PRESET_PASTEL2,
	COLOR_PRESET_CITYNIGHT,
	COLOR_PRESET_MOONLIGHT,
	COLOR_PRESET_DAZZLINGLIGHT,
	COLOR_PRESET_NEONBLAST,
	COLOR_PRESET_TOXICSWAMP,
	COLOR_PRESET_COSMICSTORM,
	COLOR_PRESET_LAVAFLOW,
	COLOR_PRESET_GOLD,
	COLOR_PRESET_MONOCHROME,
	COLOR_PRESET_TEST_COLOR,
	COLOR_PRESET_TEST_TWO,
	COLOR_PRESET_COUNT
};

// Color structure (ARGB format)
struct PresetColor {
	unsigned char a, r, g, b;
};

// Preset color palettes (8 colors each)
namespace ColorPresets {
	// レインボー (Rainbow)
	const PresetColor kRainbow[8] = {
		{255, 255, 0, 0}, {255, 255, 128, 0}, {255, 255, 255, 0}, {255, 0, 255, 0},
		{255, 0, 0, 255}, {255, 74, 0, 130}, {255, 140, 0, 255}, {255, 255, 0, 255}
	};

	// パステルレインボー (RainbowPastel)
	const PresetColor kRainbowPastel[8] = {
		{255, 255, 178, 178}, {255, 255, 217, 178}, {255, 255, 255, 178}, {255, 178, 255, 178},
		{255, 178, 178, 255}, {255, 217, 178, 255}, {255, 255, 178, 255}, {255, 255, 204, 255}
	};

	// 森 (Forest)
	const PresetColor kForest[8] = {
		{255, 102, 229, 128}, {255, 153, 242, 204}, {255, 51, 178, 229}, {255, 178, 255, 178},
		{255, 102, 204, 255}, {255, 76, 204, 102}, {255, 153, 204, 255}, {255, 204, 255, 229}
	};

	// サイバー (Cyber)
	const PresetColor kCyber[8] = {
		{255, 0, 204, 255}, {255, 128, 0, 255}, {255, 0, 255, 128}, {255, 51, 153, 255},
		{255, 255, 0, 204}, {255, 0, 102, 153}, {255, 204, 255, 0}, {255, 178, 178, 178}
	};

	// 警告 (Hazard)
	const PresetColor kHazard[8] = {
		{255, 255, 51, 0}, {255, 255, 128, 0}, {255, 0, 0, 0}, {255, 204, 0, 0},
		{255, 153, 76, 0}, {255, 51, 51, 51}, {255, 255, 178, 0}, {255, 128, 0, 0}
	};

	// 桜 (Sakura)
	const PresetColor kSakura[8] = {
		{255, 255, 178, 204}, {255, 229, 229, 242}, {255, 178, 255, 178}, {255, 255, 217, 229},
		{255, 153, 204, 102}, {255, 255, 153, 191}, {255, 242, 242, 255}, {255, 153, 204, 229}
	};

	// 砂漠 (Desert)
	const PresetColor kDesert[8] = {
		{255, 204, 153, 51}, {255, 178, 102, 0}, {255, 102, 51, 25}, {255, 229, 178, 76},
		{255, 51, 25, 12}, {255, 153, 76, 0}, {255, 128, 102, 76}, {255, 25, 12, 0}
	};

	// 星屑 (StarDust)
	const PresetColor kStarDust[8] = {
		{255, 12, 0, 51}, {255, 76, 0, 128}, {255, 229, 229, 255}, {255, 25, 25, 102},
		{255, 153, 128, 204}, {255, 51, 0, 89}, {255, 178, 178, 178}, {255, 0, 0, 25}
	};

	// 若葉 (Wakaba)
	const PresetColor kWakaba[8] = {
		{255, 204, 255, 51}, {255, 153, 229, 102}, {255, 255, 229, 0}, {255, 102, 204, 76},
		{255, 229, 255, 128}, {255, 178, 242, 153}, {255, 255, 255, 153}, {255, 76, 178, 51}
	};

	// 危険地帯 (DangerZone)
	const PresetColor kDangerZone[8] = {
		{255, 0, 0, 0}, {255, 255, 204, 0}, {255, 255, 102, 0}, {255, 51, 51, 51},
		{255, 229, 178, 0}, {255, 204, 76, 0}, {255, 25, 25, 25}, {255, 255, 153, 0}
	};

	// 妖艶 (Yoen)
	const PresetColor kYoen[8] = {
		{255, 102, 0, 128}, {255, 153, 0, 204}, {255, 51, 0, 76}, {255, 204, 25, 76},
		{255, 76, 25, 102}, {255, 229, 0, 153}, {255, 25, 0, 38}, {255, 178, 51, 229}
	};

	// 爽快 (Sokai)
	const PresetColor kSokai[8] = {
		{255, 0, 178, 255}, {255, 76, 255, 178}, {255, 204, 242, 255}, {255, 0, 128, 204},
		{255, 128, 255, 204}, {255, 25, 229, 255}, {255, 229, 255, 242}, {255, 0, 153, 229}
	};

	// 夢幻の風 (DreamyWind)
	const PresetColor kDreamyWind[8] = {
		{255, 153, 229, 255}, {255, 255, 191, 229}, {255, 204, 255, 255}, {255, 255, 204, 242},
		{255, 102, 204, 255}, {255, 255, 166, 204}, {255, 229, 242, 255}, {255, 255, 204, 217}
	};

	// 夕焼け (Sunset)
	const PresetColor kSunset[8] = {
		{255, 255, 102, 0}, {255, 255, 153, 51}, {255, 255, 204, 102}, {255, 255, 69, 0},
		{255, 255, 140, 0}, {255, 204, 85, 0}, {255, 178, 34, 34}, {255, 255, 165, 0}
	};

	// 海 (Ocean)
	const PresetColor kOcean[8] = {
		{255, 0, 119, 190}, {255, 0, 191, 255}, {255, 135, 206, 235}, {255, 0, 150, 255},
		{255, 30, 144, 255}, {255, 100, 149, 237}, {255, 173, 216, 230}, {255, 0, 206, 209}
	};

	// 秋 (Autumn)
	const PresetColor kAutumn[8] = {
		{255, 34, 139, 34}, {255, 107, 142, 35}, {255, 154, 205, 50}, {255, 255, 215, 0},
		{255, 255, 165, 0}, {255, 255, 69, 0}, {255, 220, 20, 60}, {255, 178, 34, 34}
	};

	// 雪 (Snow)
	const PresetColor kSnow[8] = {
		{255, 255, 255, 255}, {255, 240, 248, 255}, {255, 230, 230, 250}, {255, 248, 248, 255},
		{255, 220, 220, 220}, {255, 245, 245, 245}, {255, 211, 211, 211}, {255, 192, 192, 192}
	};

	// 深海 (DeepSea)
	const PresetColor kDeepSea[8] = {
		{255, 0, 0, 139}, {255, 25, 25, 112}, {255, 0, 0, 205}, {255, 72, 61, 139},
		{255, 106, 90, 205}, {255, 123, 104, 238}, {255, 147, 112, 219}, {255, 138, 43, 226}
	};

	// 朝露 (MorningDew)
	const PresetColor kMorningDew[8] = {
		{255, 255, 255, 0}, {255, 255, 165, 0}, {255, 255, 20, 147}, {255, 0, 191, 255},
		{255, 30, 144, 255}, {255, 50, 205, 50}, {255, 138, 43, 226}, {255, 255, 69, 0}
	};

	// 夜空 (NightSky)
	const PresetColor kNightSky[8] = {
		{255, 25, 25, 112}, {255, 0, 0, 139}, {255, 72, 61, 139}, {255, 106, 90, 205},
		{255, 123, 104, 238}, {255, 147, 112, 219}, {255, 138, 43, 226}, {255, 148, 0, 211}
	};

	// 炎 (Flame)
	const PresetColor kFlame[8] = {
		{255, 186, 85, 211}, {255, 221, 160, 221}, {255, 238, 130, 238}, {255, 218, 112, 214},
		{255, 255, 182, 193}, {255, 255, 192, 203}, {255, 230, 230, 250}, {255, 216, 191, 216}
	};

	// 大地 (Earth)
	const PresetColor kEarth[8] = {
		{255, 34, 139, 34}, {255, 50, 205, 50}, {255, 144, 238, 144}, {255, 255, 182, 193},
		{255, 255, 20, 147}, {255, 219, 112, 147}, {255, 186, 85, 211}, {255, 138, 43, 226}
	};

	// 宝石 (Jewel)
	const PresetColor kJewel[8] = {
		{255, 255, 0, 255}, {255, 0, 255, 255}, {255, 255, 215, 0}, {255, 50, 205, 50},
		{255, 255, 20, 147}, {255, 30, 144, 255}, {255, 138, 43, 226}, {255, 255, 105, 180}
	};

	// パステル2 (Pastel2)
	const PresetColor kPastel2[8] = {
		{255, 255, 182, 193}, {255, 255, 218, 185}, {255, 255, 228, 196}, {255, 255, 240, 245},
		{255, 230, 230, 250}, {255, 221, 160, 221}, {255, 255, 228, 225}, {255, 255, 218, 185}
	};

	// 夜の街 (CityNight)
	const PresetColor kCityNight[8] = {
		{255, 101, 67, 33}, {255, 139, 69, 19}, {255, 160, 82, 45}, {255, 205, 133, 63},
		{255, 222, 184, 135}, {255, 238, 203, 173}, {255, 245, 222, 179}, {255, 255, 228, 196}
	};

	// 月光 (Moonlight)
	const PresetColor kMoonlight[8] = {
		{255, 248, 248, 255}, {255, 230, 230, 250}, {255, 176, 196, 222}, {255, 119, 136, 153},
		{255, 112, 128, 144}, {255, 135, 206, 235}, {255, 173, 216, 230}, {255, 240, 248, 255}
	};

	// 眩光 (DazzlingLight)
	const PresetColor kDazzlingLight[8] = {
		{255, 255, 255, 255}, {255, 255, 255, 224}, {255, 255, 250, 205}, {255, 255, 255, 0},
		{255, 255, 215, 0}, {255, 255, 228, 181}, {255, 255, 248, 220}, {255, 255, 255, 240}
	};

	// ネオンブラスト (NeonBlast)
	const PresetColor kNeonBlast[8] = {
		{255, 255, 0, 255}, {255, 255, 20, 147}, {255, 255, 105, 180}, {255, 219, 112, 147},
		{255, 186, 85, 211}, {255, 138, 43, 226}, {255, 148, 0, 211}, {255, 199, 21, 133}
	};

	// 毒沼 (ToxicSwamp)
	const PresetColor kToxicSwamp[8] = {
		{255, 255, 0, 0}, {255, 255, 69, 0}, {255, 255, 140, 0}, {255, 255, 165, 0},
		{255, 255, 255, 0}, {255, 255, 215, 0}, {255, 139, 0, 0}, {255, 128, 0, 0}
	};

	// 宇宙嵐 (CosmicStorm)
	const PresetColor kCosmicStorm[8] = {
		{255, 0, 255, 127}, {255, 46, 139, 87}, {255, 0, 250, 154}, {255, 127, 255, 212},
		{255, 173, 216, 230}, {255, 138, 43, 226}, {255, 147, 112, 219}, {255, 255, 20, 147}
	};

	// 溶岩流 (LavaFlow)
	const PresetColor kLavaFlow[8] = {
		{255, 255, 0, 0}, {255, 255, 69, 0}, {255, 255, 20, 147}, {255, 139, 0, 0},
		{255, 255, 140, 0}, {255, 220, 20, 60}, {255, 178, 34, 34}, {255, 128, 0, 0}
	};

	// 金 (Gold)
	const PresetColor kGold[8] = {
		{255, 255, 215, 0}, {255, 255, 223, 0}, {255, 255, 255, 0}, {255, 255, 218, 185},
		{255, 238, 203, 173}, {255, 205, 133, 63}, {255, 184, 134, 11}, {255, 139, 69, 19}
	};

	// モノクロ (Monochrome)
	const PresetColor kMonochrome[8] = {
		{255, 255, 255, 255}, {255, 240, 240, 240}, {255, 211, 211, 211}, {255, 169, 169, 169},
		{255, 128, 128, 128}, {255, 105, 105, 105}, {255, 64, 64, 64}, {255, 0, 0, 0}
	};

	// テストカラー (test_color)
	const PresetColor ktest_color[8] = {
		{255, 255, 0, 0}, {255, 255, 128, 0}, {255, 255, 255, 0}, {255, 0, 255, 0},
		{255, 0, 0, 255}, {255, 74, 0, 130}, {255, 140, 0, 255}, {255, 255, 0, 255}
	};

	// test_two (test_two)
	const PresetColor ktest_two[8] = {
		{255, 76, 25, 102}, {255, 76, 25, 103}, {255, 76, 25, 104}, {255, 76, 25, 105},
		{255, 76, 25, 106}, {255, 76, 25, 107}, {255, 76, 25, 108}, {255, 76, 25, 109}
	};
}

// Preset color lookup table
inline const PresetColor* GetPresetPalette(int presetIndex) {
	switch (presetIndex) {
		case 1: return ColorPresets::kRainbow;
		case 2: return ColorPresets::kRainbowPastel;
		case 3: return ColorPresets::kForest;
		case 4: return ColorPresets::kCyber;
		case 5: return ColorPresets::kHazard;
		case 6: return ColorPresets::kSakura;
		case 7: return ColorPresets::kDesert;
		case 8: return ColorPresets::kStarDust;
		case 9: return ColorPresets::kWakaba;
		case 10: return ColorPresets::kDangerZone;
		case 11: return ColorPresets::kYoen;
		case 12: return ColorPresets::kSokai;
		case 13: return ColorPresets::kDreamyWind;
		case 14: return ColorPresets::kSunset;
		case 15: return ColorPresets::kOcean;
		case 16: return ColorPresets::kAutumn;
		case 17: return ColorPresets::kSnow;
		case 18: return ColorPresets::kDeepSea;
		case 19: return ColorPresets::kMorningDew;
		case 20: return ColorPresets::kNightSky;
		case 21: return ColorPresets::kFlame;
		case 22: return ColorPresets::kEarth;
		case 23: return ColorPresets::kJewel;
		case 24: return ColorPresets::kPastel2;
		case 25: return ColorPresets::kCityNight;
		case 26: return ColorPresets::kMoonlight;
		case 27: return ColorPresets::kDazzlingLight;
		case 28: return ColorPresets::kNeonBlast;
		case 29: return ColorPresets::kToxicSwamp;
		case 30: return ColorPresets::kCosmicStorm;
		case 31: return ColorPresets::kLavaFlow;
		case 32: return ColorPresets::kGold;
		case 33: return ColorPresets::kMonochrome;
		case 34: return ColorPresets::ktest_color;
		case 35: return ColorPresets::ktest_two;
		default: return ColorPresets::kRainbow;  // Fallback to first preset
	}
}

#endif // SDK_PROCAMP_COLOR_PRESETS_H
