#!/bin/bash
# macOS Code Signing Setup Script
# OST_WindyLines プラグイン署名準備

set -e  # エラーで停止

# 色付き出力
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}OST_WindyLines - macOS 署名準備${NC}"
echo -e "${BLUE}========================================${NC}\n"

# Step 1: Apple Developer Program 登録確認
echo -e "${YELLOW}[Step 1] Apple Developer Program 登録確認${NC}"
echo ""
echo "Apple Developer Program への登録が必要です。"
echo "URL: https://developer.apple.com/programs/"
echo ""
echo "年間費用: $99 USD"
echo "登録には1-2営業日かかります。"
echo ""
read -p "既に登録済みですか？ (y/n): " REGISTERED

if [ "$REGISTERED" != "y" ]; then
    echo -e "${RED}✗${NC} まず Apple Developer Program に登録してください。"
    echo "  1. https://developer.apple.com/programs/ にアクセス"
    echo "  2. 'Enroll' をクリック"
    echo "  3. Apple ID でサインイン"
    echo "  4. 個人/組織を選択して登録"
    echo ""
    echo "登録完了後、このスクリプトを再実行してください。"
    exit 1
fi

echo -e "${GREEN}✓${NC} Apple Developer Program 登録確認完了\n"

# Step 2: 証明書の存在確認
echo -e "${YELLOW}[Step 2] コード署名証明書の確認${NC}"
echo ""

CERT_COUNT=$(security find-identity -v -p codesigning | grep "Developer ID Application" | wc -l | xargs)

if [ "$CERT_COUNT" -eq 0 ]; then
    echo -e "${RED}✗${NC} Developer ID Application 証明書が見つかりません。"
    echo ""
    echo "証明書の作成方法:"
    echo "  1. https://developer.apple.com/account/resources/certificates/list にアクセス"
    echo "  2. '+' ボタンをクリック"
    echo "  3. 'Developer ID Application' を選択"
    echo "  4. CSR (Certificate Signing Request) をアップロード"
    echo ""
    echo "CSR の作成:"
    echo "  1. Keychain Access.app を開く"
    echo "  2. メニュー: Keychain Access > Certificate Assistant > Request a Certificate from a Certificate Authority"
    echo "  3. User Email Address: あなたのメールアドレス"
    echo "  4. Common Name: Kiyoto Nakamura"
    echo "  5. 'Saved to disk' を選択"
    echo "  6. 生成された CertificateSigningRequest.certSigningRequest をアップロード"
    echo ""
    echo "証明書ダウンロード後:"
    echo "  - .cer ファイルをダブルクリックして Keychain にインストール"
    echo ""
    read -p "証明書をインストールしましたか？ (y/n): " CERT_INSTALLED
    
    if [ "$CERT_INSTALLED" != "y" ]; then
        echo -e "${RED}証明書をインストールしてから再実行してください。${NC}"
        exit 1
    fi
    
    # 再確認
    CERT_COUNT=$(security find-identity -v -p codesigning | grep "Developer ID Application" | wc -l | xargs)
    if [ "$CERT_COUNT" -eq 0 ]; then
        echo -e "${RED}✗${NC} まだ証明書が検出されません。Keychain を確認してください。"
        exit 1
    fi
fi

echo -e "${GREEN}✓${NC} Developer ID Application 証明書が見つかりました。"
echo ""
security find-identity -v -p codesigning | grep "Developer ID Application"
echo ""

# Team ID の確認
echo -e "${YELLOW}[Step 3] Team ID の確認${NC}"
echo ""
echo "Apple Developer アカウントの Team ID を確認してください。"
echo "URL: https://developer.apple.com/account"
echo "画面右上の 'Membership' セクションに表示されています。"
echo ""
read -p "Team ID を入力してください (10文字の英数字): " TEAM_ID

if [ -z "$TEAM_ID" ]; then
    echo -e "${RED}✗${NC} Team ID が必要です。"
    exit 1
fi

echo -e "${GREEN}✓${NC} Team ID: $TEAM_ID\n"

# Step 4: App-Specific Password の作成
echo -e "${YELLOW}[Step 4] App-Specific Password (公証用)${NC}"
echo ""
echo "公証 (Notarization) には App-Specific Password が必要です。"
echo ""
echo "作成方法:"
echo "  1. https://appleid.apple.com にアクセス"
echo "  2. 'Sign-In and Security' > 'App-Specific Passwords' をクリック"
echo "  3. '+' ボタンで新規作成"
echo "  4. 名前: 'OST_WindyLines_Notarization'"
echo "  5. 生成されたパスワードをコピー (xxxx-xxxx-xxxx-xxxx 形式)"
echo ""
read -p "App-Specific Password を作成しましたか？ (y/n): " APP_PWD_CREATED

if [ "$APP_PWD_CREATED" != "y" ]; then
    echo -e "${YELLOW}後で作成してください。公証時に必要になります。${NC}"
fi

# Keychain への保存
if [ "$APP_PWD_CREATED" = "y" ]; then
    echo ""
    read -sp "App-Specific Password を入力 (非表示): " APP_PASSWORD
    echo ""
    read -p "Apple ID (メールアドレス) を入力: " APPLE_ID
    
    echo ""
    echo "Keychain に保存中..."
    xcrun notarytool store-credentials "AC_PASSWORD" \
        --apple-id "$APPLE_ID" \
        --team-id "$TEAM_ID" \
        --password "$APP_PASSWORD" 2>&1 || {
        echo -e "${RED}✗${NC} Keychain への保存に失敗しました。"
        echo "手動で保存してください:"
        echo "  xcrun notarytool store-credentials AC_PASSWORD \\"
        echo "    --apple-id \"$APPLE_ID\" \\"
        echo "    --team-id \"$TEAM_ID\" \\"
        echo "    --password \"<your-app-specific-password>\""
    }
    echo -e "${GREEN}✓${NC} Keychain に保存されました (プロファイル名: AC_PASSWORD)\n"
fi

# Step 5: 設定ファイルの生成
echo -e "${YELLOW}[Step 5] 署名設定ファイルの生成${NC}"
echo ""

CERT_NAME=$(security find-identity -v -p codesigning | grep "Developer ID Application" | head -1 | sed 's/.*"\(.*\)".*/\1/')

cat > "$(dirname "$0")/codesign_config.sh" << EOF
#!/bin/bash
# Auto-generated by codesign_setup.sh
# DO NOT EDIT MANUALLY

export CODESIGN_IDENTITY="$CERT_NAME"
export TEAM_ID="$TEAM_ID"
export APPLE_ID="${APPLE_ID:-your@email.com}"
export KEYCHAIN_PROFILE="AC_PASSWORD"
EOF

chmod +x "$(dirname "$0")/codesign_config.sh"

echo -e "${GREEN}✓${NC} 設定ファイルを生成しました: codesign_config.sh\n"

# 完了
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}セットアップ完了！${NC}"
echo -e "${GREEN}========================================${NC}\n"

echo "次のステップ:"
echo "  1. ./Mac/codesign_plugin.sh を実行してプラグインに署名"
echo "  2. ./Mac/notarize_plugin.sh を実行して公証"
echo ""
