#!/bin/bash
# Auto-generated by codesign_setup.sh
# DO NOT EDIT MANUALLY

export CODESIGN_IDENTITY="Developer ID Application: Kiyoto Nakamura (K6BMA3VLGX)"
export TEAM_ID="K6BMA3VLGX"
export APPLE_ID="murocoboy.business@gmail.com"
export KEYCHAIN_PROFILE="AC_PASSWORD"
export ENTITLEMENTS_PATH="Mac/OST_WindyLines.entitlements.plist"
