#!/usr/bin/env python3
"""
カラープリセット TSV → C++ヘッダー自動生成ツール

使い方:
    python color_preset_converter.py

入力: color_presets.tsv
出力: TEMPLATE_Plugin_ColorPresets.h (自動生成、DO NOT EDIT)

TSV形式（タブ区切り）:
    id  name  name_en  color1  color2  ... color8
    各色は "A,R,G,B" 形式（0-255）

NOTE: このスクリプトはテンプレートです。
      init_project.sh でプロジェクト名が自動置換されます。
"""

import csv
import sys
import os

# 設定（init_project.sh で置換される）
TSV_FILE = "color_presets.tsv"
OUTPUT_FILE = "__TPL_MATCH_NAME___ColorPresets.h"
HEADER_GUARD = "__TPL_UPPER_PREFIX_____TPL_UPPER_PLUGIN___COLOR_PRESETS_H"
NAMESPACE = "ColorPresets"
MAX_COLORS_PER_PRESET = 8


def parse_color(color_str):
    """'A,R,G,B' 文字列をタプルに変換"""
    parts = [int(x.strip()) for x in color_str.split(',')]
    if len(parts) != 4:
        raise ValueError(f"Invalid color format: {color_str}")
    return tuple(parts)


def generate_header(presets):
    """C++ヘッダーを生成"""
    lines = []
    lines.append(f"// Auto-generated by color_preset_converter.py — DO NOT EDIT")
    lines.append(f"// Source: {TSV_FILE}")
    lines.append(f"// Presets: {len(presets)}")
    lines.append(f"")
    lines.append(f"#ifndef {HEADER_GUARD}")
    lines.append(f"#define {HEADER_GUARD}")
    lines.append(f"")
    lines.append(f"struct PresetColor {{")
    lines.append(f"    unsigned char a, r, g, b;")
    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"static const int kColorPresetCount = {len(presets)};")
    lines.append(f"")

    # 各プリセットのカラーデータ
    lines.append(f"namespace {NAMESPACE} {{")
    for preset in presets:
        pid = preset['id']
        name = preset['name']
        name_en = preset['name_en']
        lines.append(f"    // [{pid}] {name} ({name_en})")
        lines.append(f"    static const PresetColor kPreset_{name_en}[{MAX_COLORS_PER_PRESET}] = {{")
        for i in range(MAX_COLORS_PER_PRESET):
            color = preset['colors'][i]
            comma = "," if i < MAX_COLORS_PER_PRESET - 1 else ""
            lines.append(f"        {{{color[0]}, {color[1]}, {color[2]}, {color[3]}}}{comma}")
        lines.append(f"    }};")
    lines.append(f"")

    # インデックスからパレットを取得する関数
    lines.append(f"    static const PresetColor* GetPresetPalette(int index) {{")
    lines.append(f"        switch (index) {{")
    for i, preset in enumerate(presets):
        lines.append(f"            case {i}: return kPreset_{preset['name_en']};")
    lines.append(f"            default: return kPreset_{presets[0]['name_en']};")
    lines.append(f"        }}")
    lines.append(f"    }}")
    lines.append(f"}} // namespace {NAMESPACE}")
    lines.append(f"")
    lines.append(f"#endif // {HEADER_GUARD}")

    return "\n".join(lines) + "\n"


def main():
    if not os.path.exists(TSV_FILE):
        print(f"Error: {TSV_FILE} not found")
        sys.exit(1)

    presets = []
    with open(TSV_FILE, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            preset = {
                'id': int(row['id']),
                'name': row['name'],
                'name_en': row['name_en'],
                'colors': []
            }
            for i in range(1, MAX_COLORS_PER_PRESET + 1):
                color_key = f'color{i}'
                if color_key in row and row[color_key].strip():
                    preset['colors'].append(parse_color(row[color_key]))
                else:
                    preset['colors'].append((255, 255, 255, 255))
            presets.append(preset)

    header = generate_header(presets)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(header)

    print(f"Generated {OUTPUT_FILE} ({len(presets)} presets)")


if __name__ == '__main__':
    main()
