#!/usr/bin/env python3
"""
エフェクトプリセット TSV → C++ヘッダー自動生成ツール

使い方:
    python preset_converter.py

入力: presets.tsv
出力: TEMPLATE_Plugin_Presets.h (自動生成、DO NOT EDIT)

TSV形式:
    プロジェクト固有のプリセット構造体フィールドに合わせてカスタマイズすること

NOTE: このスクリプトはテンプレートです。
      EffectPreset 構造体のフィールドに合わせて修正してください。
"""

import csv
import sys
import os

TSV_FILE = "presets.tsv"
OUTPUT_FILE = "__TPL_MATCH_NAME___Presets.h"
HEADER_GUARD = "__TPL_UPPER_PREFIX_____TPL_UPPER_PLUGIN___PRESETS_H"


def main():
    if not os.path.exists(TSV_FILE):
        print(f"Error: {TSV_FILE} not found")
        print("Generating empty preset header...")
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(f"// Auto-generated by preset_converter.py — DO NOT EDIT\n")
            f.write(f"// No presets defined yet. Add rows to {TSV_FILE} and re-run.\n")
            f.write(f"\n")
            f.write(f"#ifndef {HEADER_GUARD}\n")
            f.write(f"#define {HEADER_GUARD}\n")
            f.write(f"\n")
            f.write(f"static const int kEffectPresetCount = 0;\n")
            f.write(f"// static const EffectPreset kEffectPresets[] = {{}};\n")
            f.write(f"\n")
            f.write(f"#endif // {HEADER_GUARD}\n")
        return

    presets = []
    with open(TSV_FILE, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            presets.append(row)

    lines = []
    lines.append(f"// Auto-generated by preset_converter.py — DO NOT EDIT")
    lines.append(f"// Source: {TSV_FILE}")
    lines.append(f"// Presets: {len(presets)}")
    lines.append(f"")
    lines.append(f"#ifndef {HEADER_GUARD}")
    lines.append(f"#define {HEADER_GUARD}")
    lines.append(f"")
    lines.append(f"static const int kEffectPresetCount = {len(presets)};")
    lines.append(f"")
    lines.append(f"// TODO: EffectPreset構造体のフィールドに合わせて修正")
    lines.append(f"// static const EffectPreset kEffectPresets[kEffectPresetCount] = {{")
    for i, preset in enumerate(presets):
        comma = "," if i < len(presets) - 1 else ""
        lines.append(f"//     {{ /* {preset.get('name', f'Preset{i}')} */ }}{comma}")
    lines.append(f"// }};")
    lines.append(f"")
    lines.append(f"#endif // {HEADER_GUARD}")

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {OUTPUT_FILE} ({len(presets)} presets)")


if __name__ == '__main__':
    main()
