/**
 * OST_WindyLines_Encoding.h
 * 
 * Mac/Windows 共通で使用可能な日本語パラメータ名エンコーディングヘルパー
 * Premiere Pro がパラメータ名を Shift_JIS として読み込むため、
 * Mac では事前に変換した Shift_JIS バイト列を使用する
 * 
 * 使用方法:
 * 1. このヘッダーをインクルード
 * 2. パラメータ名に PARAM_XXX マクロを使用
 * 
 * 例:
 *   PF_ADD_FLOAT_SLIDERX(PARAM_LINE_COUNT, ...);
 */

#ifndef OST_WINDYLINES_ENCODING_H
#define OST_WINDYLINES_ENCODING_H

// ========================================
// Shift_JIS バイト列定義 (Mac用)
// Generated by generate_sjis_macros.sh
// ========================================

// 基本設定
// "ライン数"
#define SJIS_LINE_COUNT "\x83\x89\x83\x43\x83\x93\x90\x94"

// "寿命(フレーム)"
#define SJIS_LIFETIME "\x8e\xf5\x96\xbd\x28\x83\x74\x83\x8c\x81\x5b\x83\x80\x29"

// "移動距離(px)"
#define SJIS_TRAVEL "\x88\xda\x93\xae\x8b\x97\x97\xa3\x28\x70\x78\x29"

// "ランダムシード"
#define SJIS_SEED "\x83\x89\x83\x93\x83\x5f\x83\x80\x83\x56\x81\x5b\x83\x68"

// カラー設定
// "カラーモード"
#define SJIS_COLOR_MODE "\x83\x4a\x83\x89\x81\x5b\x83\x82\x81\x5b\x83\x68"

// "単色"
#define SJIS_SINGLE_COLOR "\x92\x50\x90\x46"

// "プリセット"
#define SJIS_PRESET "\x83\x76\x83\x8a\x83\x5a\x83\x62\x83\x67"

// "カスタム"
#define SJIS_CUSTOM "\x83\x4a\x83\x58\x83\x5e\x83\x80"

// "色"
#define SJIS_COLOR "\x90\x46"

// "カスタム1" - "カスタム8"
#define SJIS_CUSTOM_1 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x31"
#define SJIS_CUSTOM_2 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x32"
#define SJIS_CUSTOM_3 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x33"
#define SJIS_CUSTOM_4 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x34"
#define SJIS_CUSTOM_5 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x35"
#define SJIS_CUSTOM_6 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x36"
#define SJIS_CUSTOM_7 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x37"
#define SJIS_CUSTOM_8 "\x83\x4a\x83\x58\x83\x5e\x83\x80\x38"

// 外観
// "太さ(px)"
#define SJIS_THICKNESS "\x91\xbe\x82\xb3\x28\x70\x78\x29"

// "長さ(px)"
#define SJIS_LENGTH "\x92\xb7\x82\xb3\x28\x70\x78\x29"

// "端のスタイル"
#define SJIS_LINE_CAP "\x92\x5b\x82\xcc\x83\x58\x83\x5e\x83\x43\x83\x8b"

// "角度"
#define SJIS_ANGLE "\x8a\x70\x93\x78"

// "アンチエイリアス"
#define SJIS_AA "\x83\x41\x83\x93\x83\x60\x83\x47\x83\x43\x83\x8a\x83\x41\x83\x58"

// "テールフェード"
#define SJIS_TAIL_FADE "\x83\x65\x81\x5b\x83\x8b\x83\x74\x83\x46\x81\x5b\x83\x68"

// 位置
// "風の起点"
#define SJIS_ORIGIN_MODE "\x95\x97\x82\xcc\x8b\x4e\x93\x5f"

// "発生間隔(フレーム)"
#define SJIS_INTERVAL "\x94\xad\x90\xb6\x8a\xd4\x8a\x75\x28\x83\x74\x83\x8c\x81\x5b\x83\x80\x29"

// "スポーンエリアX(%)"
#define SJIS_SPAWN_SCALE_X "\x83\x58\x83\x7c\x81\x5b\x83\x93\x83\x47\x83\x8a\x83\x41\x58\x28\x25\x29"

// "スポーンエリアY(%)"
#define SJIS_SPAWN_SCALE_Y "\x83\x58\x83\x7c\x81\x5b\x83\x93\x83\x47\x83\x8a\x83\x41\x59\x28\x25\x29"

// "スポーンエリア回転"
#define SJIS_SPAWN_ROTATION "\x83\x58\x83\x7c\x81\x5b\x83\x93\x83\x47\x83\x8a\x83\x41\x89\xf1\x93\x5d"

// "スポーンエリア表示"
#define SJIS_SHOW_SPAWN "\x83\x58\x83\x7c\x81\x5b\x83\x93\x83\x47\x83\x8a\x83\x41\x95\x5c\x8e\xa6"

// "スポーンエリア色"
#define SJIS_SPAWN_COLOR "\x83\x58\x83\x7c\x81\x5b\x83\x93\x83\x47\x83\x8a\x83\x41\x90\x46"

// "オフセットX(px)"
#define SJIS_OFFSET_X "\x83\x49\x83\x74\x83\x5a\x83\x62\x83\x67\x58\x28\x70\x78\x29"

// "オフセットY(px)"
#define SJIS_OFFSET_Y "\x83\x49\x83\x74\x83\x5a\x83\x62\x83\x67\x59\x28\x70\x78\x29"

// アニメーション
// "アニメパターン"
#define SJIS_ANIM_PATTERN "\x83\x41\x83\x6a\x83\x81\x83\x70\x83\x5e\x81\x5b\x83\x93"

// "センターギャップ"
#define SJIS_CENTER_GAP "\x83\x5a\x83\x93\x83\x5e\x81\x5b\x83\x4d\x83\x83\x83\x62\x83\x76"

// "イージング"
#define SJIS_EASING "\x83\x43\x81\x5b\x83\x57\x83\x93\x83\x4f"

// "開始時間(フレーム)"
#define SJIS_START_TIME "\x8a\x4a\x8e\x6e\x8e\x9e\x8a\xd4\x28\x83\x74\x83\x8c\x81\x5b\x83\x80\x29"

// "継続時間(フレーム)"
#define SJIS_DURATION "\x8c\x70\x91\xb1\x8e\x9e\x8a\xd4\x28\x83\x74\x83\x8c\x81\x5b\x83\x80\x29"

// シャドウ
// "シャドウ"
#define SJIS_SHADOW "\x83\x56\x83\x83\x83\x68\x83\x45"

// "シャドウ有効"
#define SJIS_SHADOW_ENABLE "\x83\x56\x83\x83\x83\x68\x83\x45\x97\x4c\x8c\xf8"

// "シャドウ色"
#define SJIS_SHADOW_COLOR "\x83\x56\x83\x83\x83\x68\x83\x45\x90\x46"

// "シャドウX(px)"
#define SJIS_SHADOW_OFFSET_X "\x83\x56\x83\x83\x83\x68\x83\x45\x58\x28\x70\x78\x29"

// "シャドウY(px)"
#define SJIS_SHADOW_OFFSET_Y "\x83\x56\x83\x83\x83\x68\x83\x45\x59\x28\x70\x78\x29"

// "シャドウ不透明度"
#define SJIS_SHADOW_OPACITY "\x83\x56\x83\x83\x83\x68\x83\x45\x95\x73\x93\xa7\x96\xbe\x93\x78"

// 詳細設定
// "エレメント非表示"
#define SJIS_HIDE_ELEMENT "\x83\x47\x83\x8c\x83\x81\x83\x93\x83\x67\x94\xf1\x95\x5c\x8e\xa6"

// "ブレンドモード"
#define SJIS_BLEND_MODE "\x83\x75\x83\x8c\x83\x93\x83\x68\x83\x82\x81\x5b\x83\x68"

// "深度強度"
#define SJIS_DEPTH_STRENGTH "\x90\x5b\x93\x78\x8b\xad\x93\x78"

// "アルファ閾値"
#define SJIS_ALPHA_THRESH "\x83\x41\x83\x8b\x83\x74\x83\x40\xe8\x87\x92\x6c"

// "モーションブラー"
#define SJIS_MOTION_BLUR "\x83\x82\x81\x5b\x83\x56\x83\x87\x83\x93\x83\x75\x83\x89\x81\x5b"

// "ブラー品質"
#define SJIS_BLUR_SAMPLES "\x83\x75\x83\x89\x81\x5b\x95\x69\x8e\xbf"

// "ブラー強度"
#define SJIS_BLUR_STRENGTH "\x83\x75\x83\x89\x81\x5b\x8b\xad\x93\x78"

// "ブラータイプ"
#define SJIS_BLUR_TYPE "\x83\x75\x83\x89\x81\x5b\x83\x5e\x83\x43\x83\x76"

// "双方向|トレイル"
#define SJIS_BLUR_TYPE_MENU "\x91\x6f\x95\xfb\x8c\xfc\x7c\x83\x67\x83\x8c\x83\x43\x83\x8b"

// "速度連動"
#define SJIS_BLUR_VELOCITY "\x91\xac\x93\x78\x98\x41\x93\xae"

// エフェクトプリセット
// "エフェクトプリセット"
#define SJIS_EFFECT_PRESET "\x83\x47\x83\x74\x83\x46\x83\x4e\x83\x67\x83\x76\x83\x8a\x83\x5a\x83\x62\x83\x67"

// "デフォルト"
#define SJIS_DEFAULT "\x83\x66\x83\x74\x83\x48\x83\x8b\x83\x67"

// ポップアップメニュー項目
// "単色|プリセット|カスタム"
#define SJIS_COLOR_MODE_MENU "\x92\x50\x90\x46\x7c\x83\x76\x83\x8a\x83\x5a\x83\x62\x83\x67\x7c\x83\x4a\x83\x58\x83\x5e\x83\x80"

// "丸|四角|なし"
#define SJIS_LINE_CAP_MENU "\x8a\xdb\x7c\x8e\x6c\x8a\x70\x7c\x82\xc8\x82\xb5"

// ========================================
// プラットフォーム別マクロ
// Windows: UTF-8ソースからコンパイラが自動変換
// Mac: Shift_JIS バイト列を直接使用
// ========================================

#ifdef _WIN32
    // Windows: /source-charset:utf-8 /execution-charset:shift_jis で自動変換
    #define PARAM_LINE_COUNT      "ライン数"
    #define PARAM_LIFETIME        "寿命(フレーム)"
    #define PARAM_TRAVEL          "移動距離(px)"
    #define PARAM_SEED            "ランダムシード"
    #define PARAM_COLOR_MODE      "カラーモード"
    #define PARAM_SINGLE_COLOR    "単色"
    #define PARAM_PRESET          "プリセット"
    #define PARAM_CUSTOM          "カスタム"
    #define PARAM_COLOR           "色"
    #define PARAM_CUSTOM_1        "カスタム1"
    #define PARAM_CUSTOM_2        "カスタム2"
    #define PARAM_CUSTOM_3        "カスタム3"
    #define PARAM_CUSTOM_4        "カスタム4"
    #define PARAM_CUSTOM_5        "カスタム5"
    #define PARAM_CUSTOM_6        "カスタム6"
    #define PARAM_CUSTOM_7        "カスタム7"
    #define PARAM_CUSTOM_8        "カスタム8"
    #define PARAM_THICKNESS       "太さ(px)"
    #define PARAM_LENGTH          "長さ(px)"
    #define PARAM_LINE_CAP        "端のスタイル"
    #define PARAM_ANGLE           "角度"
    #define PARAM_AA              "アンチエイリアス"
    #define PARAM_TAIL_FADE       "テールフェード"
    #define PARAM_ORIGIN_MODE     "風の起点"
    #define PARAM_INTERVAL        "発生間隔(フレーム)"
    #define PARAM_SPAWN_SCALE_X   "スポーンエリアX(%)"
    #define PARAM_SPAWN_SCALE_Y   "スポーンエリアY(%)"
    #define PARAM_SPAWN_ROTATION  "スポーンエリア回転"
    #define PARAM_SHOW_SPAWN      "スポーンエリア表示"
    #define PARAM_SPAWN_COLOR     "スポーンエリア色"
    #define PARAM_OFFSET_X        "オフセットX(px)"
    #define PARAM_OFFSET_Y        "オフセットY(px)"
    #define PARAM_ANIM_PATTERN    "アニメパターン"
    #define PARAM_CENTER_GAP      "センターギャップ"
    #define PARAM_EASING          "イージング"
    #define PARAM_START_TIME      "開始時間(フレーム)"
    #define PARAM_DURATION        "継続時間(フレーム)"
    #define PARAM_SHADOW          "シャドウ"
    #define PARAM_SHADOW_ENABLE   "シャドウ有効"
    #define PARAM_SHADOW_COLOR    "シャドウ色"
    #define PARAM_SHADOW_OFFSET_X "シャドウX(px)"
    #define PARAM_SHADOW_OFFSET_Y "シャドウY(px)"
    #define PARAM_SHADOW_OPACITY  "シャドウ不透明度"
    #define PARAM_HIDE_ELEMENT    "エレメント非表示"
    #define PARAM_BLEND_MODE      "ブレンドモード"
    #define PARAM_DEPTH_STRENGTH  "深度強度"
    #define PARAM_ALPHA_THRESH    "アルファ閾値"
    #define PARAM_MOTION_BLUR     "モーションブラー"
    #define PARAM_BLUR_SAMPLES    "ブラー品質"
    #define PARAM_BLUR_STRENGTH   "ブラー強度"
    #define PARAM_BLUR_TYPE       "ブラータイプ"
    #define PARAM_BLUR_TYPE_MENU  "双方向|トレイル"
    #define PARAM_BLUR_VELOCITY   "速度連動"
    #define PARAM_EFFECT_PRESET   "エフェクトプリセット"
    #define PARAM_DEFAULT         "デフォルト"
    #define PARAM_COLOR_MODE_MENU "単色|プリセット|カスタム"
    #define PARAM_LINE_CAP_MENU   "丸|四角|なし"
#else
    // Mac: Shift_JIS バイト列を直接使用
    #define PARAM_LINE_COUNT      SJIS_LINE_COUNT
    #define PARAM_LIFETIME        SJIS_LIFETIME
    #define PARAM_TRAVEL          SJIS_TRAVEL
    #define PARAM_SEED            SJIS_SEED
    #define PARAM_COLOR_MODE      SJIS_COLOR_MODE
    #define PARAM_SINGLE_COLOR    SJIS_SINGLE_COLOR
    #define PARAM_PRESET          SJIS_PRESET
    #define PARAM_CUSTOM          SJIS_CUSTOM
    #define PARAM_COLOR           SJIS_COLOR
    #define PARAM_CUSTOM_1        SJIS_CUSTOM_1
    #define PARAM_CUSTOM_2        SJIS_CUSTOM_2
    #define PARAM_CUSTOM_3        SJIS_CUSTOM_3
    #define PARAM_CUSTOM_4        SJIS_CUSTOM_4
    #define PARAM_CUSTOM_5        SJIS_CUSTOM_5
    #define PARAM_CUSTOM_6        SJIS_CUSTOM_6
    #define PARAM_CUSTOM_7        SJIS_CUSTOM_7
    #define PARAM_CUSTOM_8        SJIS_CUSTOM_8
    #define PARAM_THICKNESS       SJIS_THICKNESS
    #define PARAM_LENGTH          SJIS_LENGTH
    #define PARAM_LINE_CAP        SJIS_LINE_CAP
    #define PARAM_ANGLE           SJIS_ANGLE
    #define PARAM_AA              SJIS_AA
    #define PARAM_TAIL_FADE       SJIS_TAIL_FADE
    #define PARAM_ORIGIN_MODE     SJIS_ORIGIN_MODE
    #define PARAM_INTERVAL        SJIS_INTERVAL
    #define PARAM_SPAWN_SCALE_X   SJIS_SPAWN_SCALE_X
    #define PARAM_SPAWN_SCALE_Y   SJIS_SPAWN_SCALE_Y
    #define PARAM_SPAWN_ROTATION  SJIS_SPAWN_ROTATION
    #define PARAM_SHOW_SPAWN      SJIS_SHOW_SPAWN
    #define PARAM_SPAWN_COLOR     SJIS_SPAWN_COLOR
    #define PARAM_OFFSET_X        SJIS_OFFSET_X
    #define PARAM_OFFSET_Y        SJIS_OFFSET_Y
    #define PARAM_ANIM_PATTERN    SJIS_ANIM_PATTERN
    #define PARAM_CENTER_GAP      SJIS_CENTER_GAP
    #define PARAM_EASING          SJIS_EASING
    #define PARAM_START_TIME      SJIS_START_TIME
    #define PARAM_DURATION        SJIS_DURATION
    #define PARAM_SHADOW          SJIS_SHADOW
    #define PARAM_SHADOW_ENABLE   SJIS_SHADOW_ENABLE
    #define PARAM_SHADOW_COLOR    SJIS_SHADOW_COLOR
    #define PARAM_SHADOW_OFFSET_X SJIS_SHADOW_OFFSET_X
    #define PARAM_SHADOW_OFFSET_Y SJIS_SHADOW_OFFSET_Y
    #define PARAM_SHADOW_OPACITY  SJIS_SHADOW_OPACITY
    #define PARAM_HIDE_ELEMENT    SJIS_HIDE_ELEMENT
    #define PARAM_BLEND_MODE      SJIS_BLEND_MODE
    #define PARAM_DEPTH_STRENGTH  SJIS_DEPTH_STRENGTH
    #define PARAM_ALPHA_THRESH    SJIS_ALPHA_THRESH
    #define PARAM_MOTION_BLUR     SJIS_MOTION_BLUR
    #define PARAM_BLUR_SAMPLES    SJIS_BLUR_SAMPLES
    #define PARAM_BLUR_STRENGTH   SJIS_BLUR_STRENGTH
    #define PARAM_BLUR_TYPE       SJIS_BLUR_TYPE
    #define PARAM_BLUR_TYPE_MENU  SJIS_BLUR_TYPE_MENU
    #define PARAM_BLUR_VELOCITY   SJIS_BLUR_VELOCITY
    #define PARAM_EFFECT_PRESET   SJIS_EFFECT_PRESET
    #define PARAM_DEFAULT         SJIS_DEFAULT
    #define PARAM_COLOR_MODE_MENU SJIS_COLOR_MODE_MENU
    #define PARAM_LINE_CAP_MENU   SJIS_LINE_CAP_MENU
#endif

#endif // OST_WINDYLINES_ENCODING_H
